apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast
  namespace: forecast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forecast
  template:
    metadata:
      labels:
        app: forecast
    spec:
      containers:
      - name: forecast
        image: hebermattos/forecast:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 80